[network](../../index.md) / [com.github.kacso.androidcommons.network.exceptions](../index.md) / [UnexpectedError](index.md) / [&lt;init&gt;](./-init-.md)

# &lt;init&gt;

`UnexpectedError(cause: `[`Throwable`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html)`? = null)`

Exception thrown when there has happen some error during network call, but that error does not
belong to any other well known exception

